name: docs-ci

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.38
      - name: Generate
        run: |
          deno docs --html --name=hhash mod.ts
          touch docs/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
