name: Test CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: v${{ matrix.deno-version }} @ ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.37]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint Deno Module
        run: deno fmt --check
      - name: Test Deno Module
        run: deno test --allow-none